package fi.donhut.taskyourandroid.enumeration;

import fi.donhut.taskyourandroid.R;

public enum TASK {
	CHANGE_PROFILE_ACTIVE(R.string.TASK_CHANGE_PROFILE_ACTIVE), CHANGE_PROFILE_SILENT(R.string.TASK_CHANGE_PROFILE_SILENT), CHANGE_PROFILE_VIBRATE(R.string.TASK_CHANGE_PROFILE_VIBRATE), CHANGE_PROFILE_PLANE(R.string.TASK_CHANGE_PROFILE_PLANE),
	ENABLE_MOBILE_DATA(R.string.TASK_ENABLE_MOBILE_DATA), DISABLE_MOBILE_DATA(R.string.TASK_DISABLE_MOBILE_DATA),
	ENABLE_WIFI(R.string.TASK_ENABLE_WIFI), DISABLE_WIFI(R.string.TASK_DISABLE_WIFI),
	ENABLE_BLUETOOTH(R.string.TASK_ENABLE_BLUETOOTH), DISABLE_BLUETOOTH(R.string.TASK_DISABLE_BLUETOOTH);
	
	public int key;
	
	private TASK(int key) {
		this.key = key;
	}
	
}
